[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "pulse"
path = "./src/main.rs"

[dependencies]
clap = {version = "4.4", features = ["derive"]}
core_logic = {path = "../core_logic"}